### ISSUE TITLE
Exclude Buffers?

### ISSUE THREAD

**Issue by remlap** [notmatti/buffer_autohide#2]
Hi can this script exclude buffers I would like to leave my &bitlbee buffer always seen since its essentially a buddy list.

Thanks

**Comment by notmatti** [comment]
Hope that helps :3

**Comment by remlap** [comment]
That works really well, thank you!

**Comment by remlap** [comment]
python.buffer_autohide.excemptions = "irc.BitlBee.&bitlbee"

Doesn't seem to do anything it hides straight away.

**Comment by remlap** [comment]
It works now yes but is there away to temporarily show buffers so I can actually send a message to them?

**Comment by notmatti** [comment]
Yes, that's possible. For example, one can use `/buffer unhide <buffer>` to unhide a specific buffer or `/buffer unhide -all` to unhide all hidden buffers.

**Comment by notmatti** [comment]
It is also possible to jump to a buffer directly with `/buffer <buffer>`.

**Comment by remlap** [comment]
Thanks I set an alias to of /unhide for /buffer unhide -all how long till ones I've not selected rehide?

**Comment by notmatti** [comment]
They won't unless you cycle through your buffers by yourself.

**Comment by remlap** [comment]
Thanks for the reply.

**Comment by remlap** [comment]
> They won't unless you cycle through your buffers by yourself.

That's a shame, a feature that is possibly needed I have channels that are idle for days.
