### ISSUE TITLE
Unhide the buffer when it is visited?

### ISSUE THREAD

**Issue by jbayardo** [notmatti/buffer_autohide#3]
Perhaps it would be useful to automatically unhide the buffer when it is visited (i.e. through the /go plugin)

**Comment by notmatti** [comment]
Good idea.

My first approach was to explicitly unhide the new buffer in the `buffer_switch` callback, but sometimes they become unhidden and sometimes not. Can you confirm?

https://github.com/notmatti/buffer_autohide/blob/9e78e06ee00f9f945b8046f9b049ae1da3a4bfa8/buffer_autohide.py#L162

**Comment by 3v1n0** [comment]
Yeah, I confirm that this causes a random scenario, also the problem in such case is that it switches from other visible buffers.

And in any case, when the hidden buffer is shown, it's hidden again when moving out unless some activity is recorded (but I guess that's per #4)
